export type IndicatorAdvice = {
  title: string;
  summary: string;
  questionsToAsk: string[];
  evidenceToRequest: string[];
  vigilancePoints: string[];
  clientBenefit: string[];
};

export const indicatorAdvice: Record<number, IndicatorAdvice> = {
  1: {
    title: "Indicateur 1 — Informations diffusées au public",
    summary:
      "Vérifier que les informations publiques sont claires, accessibles et cohérentes avec les prestations réellement proposées. Le site du client est souvent la caverne aux preuves : gardez-le ouvert pendant l’audit.",
    questionsToAsk: [
      "Quel est le site ou la page principale consultée par un futur client avant de s’inscrire ?",
      "Où trouve-t-on le programme, les objectifs, les prérequis, la durée, les modalités, les tarifs ou conditions d’accès ?",
      "Les informations sur l’accessibilité handicap sont-elles visibles et faciles à trouver ?",
      "Les contacts utiles sont-ils indiqués clairement pour demander une adaptation ou un renseignement ?",
      "Si une information n’est pas sur le site, apparaît-elle dans la convention de formation ou un document transmis avant inscription ?",
    ],
    evidenceToRequest: [
      "Site internet, page offre, catalogue ou fiche prestation.",
      "Programme de formation avec objectifs, prérequis, durée, modalités et conditions d’accès.",
      "Tarifs ou modalités d’obtention du tarif lorsqu’ils ne sont pas publics.",
      "Page ou document d’accessibilité handicap visible, idéalement accessible depuis le pied de site comme les mentions légales.",
      "Coordonnées locales utiles : Agefiph, MDPH, Cap emploi, FIPHFP, ou procédure d’orientation handicap.",
      "Convention de formation si certaines informations ne sont pas publiées sur le site.",
    ],
    vigilancePoints: [
      "Beaucoup d’organismes n’ont aucune politique d’accessibilité handicap visible : c’est un point à vérifier tôt.",
      "Une page handicap générique ne suffit pas toujours : elle doit aider concrètement la personne à savoir qui contacter et vers quels relais locaux se tourner.",
      "Conseiller l’inscription à Ressource Handicap Formation lorsque c’est pertinent : c’est gratuit et utile pour structurer la démarche.",
      "Les informations publiques doivent être cohérentes entre le site, les programmes, les conventions et les documents commerciaux.",
      "Éviter les promesses trop larges ou les formulations qui laissent croire que toutes les activités sont certifiées si ce n’est pas le cas.",
    ],
    clientBenefit: [
      "Un site clair rassure les futurs clients avant même le premier contact.",
      "Des informations complètes évitent les allers-retours inutiles et les incompréhensions avant inscription.",
      "Une politique handicap visible montre que l’organisme sait accueillir, orienter et adapter si nécessaire.",
      "Une preuve bien rangée aujourd’hui, c’est une sueur froide en moins le jour de l’audit.",
    ],
  },
  2: {
    title: "Indicateur 2 — Indicateurs de résultats",
    summary:
      "Vérifier que les résultats diffusés sont compréhensibles, contextualisés et utiles. Un taux tout seul fait joli, mais sans volume ni période il raconte une histoire un peu floue.",
    questionsToAsk: [
      "Quels indicateurs de résultats sont suivis aujourd’hui ?",
      "Combien de bénéficiaires sont concernés par chaque résultat affiché ?",
      "Sur quelle période les résultats ont-ils été calculés ?",
      "Où ces résultats sont-ils communiqués au public ou aux bénéficiaires ?",
      "Qui met à jour ces indicateurs et à quelle fréquence ?",
    ],
    evidenceToRequest: [
      "Tableau de suivi des résultats.",
      "Taux de satisfaction, réussite, atteinte des objectifs, abandon ou insertion selon le contexte.",
      "Nombre de bénéficiaires concernés par chaque taux.",
      "Période observée : année, session, cohorte ou plage de dates.",
      "Page web, plaquette, catalogue ou support où les résultats sont diffusés.",
    ],
    vigilancePoints: [
      "Éviter les chiffres isolés sans contexte : 100 % sur deux personnes ne raconte pas la même chose que 100 % sur cent personnes.",
      "Un taux affiché doit permettre de comprendre le volume et la période observée.",
      "Les indicateurs doivent être adaptés à l’activité réelle : formation courte, certification, bilan de compétences, VAE, apprentissage.",
      "Vérifier que les données diffusées sont à jour et cohérentes avec les documents internes.",
      "Ne pas confondre indicateur suivi en interne et résultat réellement communiqué au public.",
    ],
    clientBenefit: [
      "Des indicateurs contextualisés renforcent la crédibilité commerciale.",
      "Le client évite les interprétations bancales ou les chiffres qui semblent sortis d’un chapeau.",
      "Les résultats deviennent un outil de pilotage, pas seulement une ligne à remplir pour Qualiopi.",
      "Une présentation claire aide le futur bénéficiaire à comprendre la fiabilité de l’organisme.",
    ],
  },
  3: {
    title: "Indicateur 3 — Adéquation programme / certification",
    summary:
      "Vérifier que la formation prépare réellement à la certification RNCP ou RS visée. Avoir le programme d’un côté et le référentiel de l’autre ne suffit pas toujours : il faut montrer le pont entre les deux.",
    questionsToAsk: [
      "La formation est-elle bien rattachée à une certification RNCP ou RS ?",
      "Le client peut-il expliquer comment le programme couvre les compétences du référentiel ?",
      "Existe-t-il un tableau de correspondance entre référentiel, modules du programme et évaluations ?",
      "Les modalités d’évaluation permettent-elles de vérifier les compétences attendues ?",
      "Les informations diffusées au public sont-elles cohérentes avec la fiche RNCP ou RS ?",
    ],
    evidenceToRequest: [
      "Fiche RNCP ou RS à jour.",
      "Programme détaillé de la formation.",
      "Référentiel de compétences ou d’activités.",
      "Tableau de correspondance entre compétences du référentiel, objectifs/modules/chapitres du programme et modalités d’évaluation.",
      "Modalités d’évaluation ou grille permettant de vérifier les compétences visées.",
    ],
    vigilancePoints: [
      "Ne pas considérer qu’un programme et un référentiel séparés suffisent : l’auditeur doit comprendre le lien.",
      "Le tableau de correspondance doit montrer clairement que la formation prépare bien à la certification visée.",
      "Attention aux formations qui annoncent une certification sans couvrir toutes les compétences nécessaires.",
      "Les habilitations, SST, PSC, habilitations électriques ou attestations simples ne sont pas des certifications RNCP/RS pour ce champ.",
      "Vérifier que les modalités d’évaluation ne sont pas décoratives : elles doivent mesurer ce qui est annoncé.",
    ],
    clientBenefit: [
      "Le tableau de correspondance sécurise Qualiopi et rend la formation plus lisible.",
      "Il aide le client à mieux vendre la cohérence de son parcours.",
      "Il facilite l’explication au bénéficiaire : pourquoi tel module existe, à quelle compétence il répond, comment il sera évalué.",
      "Une formation bien reliée à son référentiel inspire plus confiance aux financeurs, partenaires et candidats.",
    ],
  },
  4: {
    title: "Indicateur 4 — Analyse du besoin",
    summary:
      "Vérifier que le besoin du bénéficiaire est analysé avant l’entrée en prestation, et surtout que cette analyse laisse une trace. Qualiopi n’a pas encore appris à lire dans les souvenirs : il faut une preuve.",
    questionsToAsk: [
      "Comment le besoin du bénéficiaire est-il recueilli avant l’inscription ou le démarrage ?",
      "L’analyse se fait-elle par formulaire, entretien, téléphone, présentiel ou email ?",
      "Quelle trace est conservée lorsque l’échange a lieu à l’oral ?",
      "La date et le nom du bénéficiaire apparaissent-ils dans la trace ?",
      "L’analyse montre-t-elle les attentes, le contexte, les contraintes et les adaptations éventuelles ?",
      "Comment cette analyse influence-t-elle le parcours proposé ?",
    ],
    evidenceToRequest: [
      "Questionnaire d’analyse du besoin ou fiche de recueil.",
      "Document de positionnement.",
      "Synthèse écrite ou compte rendu d’entretien.",
      "Scan de notes manuscrites si l’analyse est faite en présentiel.",
      "Email de confirmation reprenant le besoin, les attentes ou les adaptations prévues.",
      "Trace datée avec le nom du bénéficiaire et les éléments analysés.",
    ],
    vigilancePoints: [
      "Un échange téléphonique ou présentiel peut être valable, mais il doit laisser une trace exploitable.",
      "La trace doit montrer ce qui a été analysé : attentes, contexte, besoin, contraintes, adaptation éventuelle.",
      "Un questionnaire rempli puis jamais utilisé reste fragile.",
      "Attention à l’effet “formation copier-coller” : même parcours, même justification, aucune personnalisation visible.",
      "La preuve doit exister avant le démarrage, pas être reconstruite après coup en mode archéologie express.",
    ],
    clientBenefit: [
      "Une analyse du besoin tracée permet de personnaliser la prestation.",
      "Elle limite les incompréhensions, les abandons et les attentes mal cadrées.",
      "Elle donne au formateur une base solide pour adapter le parcours.",
      "Elle montre au bénéficiaire que l’organisme ne déroule pas une formation standard sans regarder son besoin réel.",
    ],
  },
  5: {
    title: "Indicateur 5 — Objectifs opérationnels et évaluables",
    summary:
      "Vérifier que les objectifs sont clairs, opérationnels et réellement évaluables. Un bon objectif doit pouvoir être observé, mesuré ou vérifié à la fin.",
    questionsToAsk: [
      "Les objectifs décrivent-ils ce que le bénéficiaire sera capable de faire ?",
      "Les objectifs sont-ils formulés avec des verbes d’action observables ?",
      "Comment le formateur vérifie-t-il que chaque objectif est atteint ?",
      "L’évaluation de fin de formation permet-elle vraiment de mesurer les objectifs annoncés ?",
      "Si l’évaluation ne mesure pas les objectifs, faut-il revoir les objectifs ou l’évaluation ?",
    ],
    evidenceToRequest: [
      "Programme de formation avec objectifs pédagogiques ou opérationnels.",
      "Évaluation de fin de formation, quiz, mise en situation, grille d’observation ou cas pratique.",
      "Correspondance entre objectifs annoncés et modalités d’évaluation.",
      "Support ou consigne expliquant au bénéficiaire comment l’atteinte des objectifs sera vérifiée.",
    ],
    vigilancePoints: [
      "Demander l’évaluation dès maintenant : elle révèle vite si les objectifs sont mesurables ou seulement jolis sur le papier.",
      "Des objectifs comme “comprendre”, “découvrir” ou “sensibiliser” doivent souvent être précisés pour devenir évaluables.",
      "Si l’évaluation ne permet pas de mesurer les objectifs, il faut ajuster l’un des deux.",
      "Attention aux objectifs très ambitieux pour une durée très courte.",
      "Un objectif opérationnel doit aider le bénéficiaire à savoir ce qu’il saura faire, pas seulement ce qu’il aura entendu.",
    ],
    clientBenefit: [
      "Des objectifs évaluables rendent la formation plus claire pour le bénéficiaire.",
      "Ils donnent au formateur une preuve solide de l’atteinte des compétences.",
      "Ils facilitent la construction des évaluations et évitent les bilans trop subjectifs.",
      "Ils renforcent la cohérence commerciale : promesse, contenu et évaluation racontent la même histoire.",
    ],
  },
  6: {
    title: "Indicateur 6 — Déroulé pédagogique, supports et adaptation",
    summary:
      "Vérifier que le déroulé pédagogique, les supports et les adaptations forment un ensemble cohérent avec le programme annoncé. Le bon document au bon moment, c’est moins de panique et plus de pilotage.",
    questionsToAsk: [
      "Le déroulé pédagogique correspond-il bien au programme diffusé au client ?",
      "Les supports de formation existent-ils réellement et sont-ils utilisés pendant la prestation ?",
      "Les supports sont-ils cohérents avec les objectifs et le niveau attendu des bénéficiaires ?",
      "Comment l’organisme adapte-t-il le rythme, les supports, les exercices ou les modalités si le besoin change ?",
      "Des adaptations ont-elles déjà été réalisées pour un bénéficiaire, une contrainte de niveau, une situation de handicap ou un format distanciel ?",
    ],
    evidenceToRequest: [
      "Déroulé pédagogique ou scénario d’animation.",
      "Supports de formation remis ou utilisés pendant la session.",
      "Programme annoncé au public ou au bénéficiaire.",
      "Exemples d’exercices, activités, cas pratiques ou mises en situation.",
      "Traces d’adaptation le cas échéant : support modifié, rythme ajusté, consigne spécifique, modalité adaptée, échange avec le bénéficiaire.",
    ],
    vigilancePoints: [
      "Un déroulé pédagogique doit raconter comment la formation se passe réellement, pas seulement répéter le programme.",
      "Les supports doivent exister et correspondre aux objectifs annoncés.",
      "Une adaptation orale ou improvisée peut être pertinente, mais elle doit laisser une trace pour devenir une preuve.",
      "Les adaptations peuvent concerner le rythme, les supports, les modalités, les exercices, le handicap, le niveau initial ou les contraintes du bénéficiaire.",
      "Attention aux supports très génériques qui ne montrent pas comment la progression pédagogique est construite.",
    ],
    clientBenefit: [
      "Un déroulé clair évite l’improvisation le jour de la formation.",
      "Il facilite la délégation à un autre formateur sans perdre la cohérence pédagogique.",
      "Des supports cohérents rassurent le bénéficiaire et renforcent la qualité perçue.",
      "Les adaptations tracées montrent que l’organisme sait piloter l’expérience apprenant, pas seulement dérouler un programme.",
    ],
  },
  7: {
    title: "Indicateur 7 — Adéquation aux exigences de la certification",
    summary:
      "Cet indicateur concerne les formations rattachées à une certification RNCP ou RS. L’objectif est de vérifier que la formation prépare réellement aux exigences de la certification visée, et pas seulement qu’elle porte vaguement le même titre.",
    questionsToAsk: [
      "La formation prépare-t-elle bien à une certification RNCP ou RS identifiée ?",
      "Le client dispose-t-il du référentiel de certification à jour ?",
      "Le programme couvre-t-il toutes les compétences attendues dans le référentiel ?",
      "Les modalités d’évaluation prévues dans la formation sont-elles cohérentes avec les exigences de la certification ?",
      "Le client peut-il expliquer le lien entre son programme et la certification visée ?",
    ],
    evidenceToRequest: [
      "Référentiel RNCP ou RS.",
      "Programme de formation.",
      "Tableau de correspondance entre référentiel, objectifs, modules et évaluations.",
      "Modalités d’évaluation.",
      "Éléments transmis aux bénéficiaires sur la certification visée.",
    ],
    vigilancePoints: [
      "Avoir le programme et le référentiel côte à côte ne suffit pas toujours. Il faut idéalement une preuve qui montre le lien entre les deux.",
      "Sans tableau de correspondance, c’est un peu comme dire “les deux documents sont dans la même pièce, donc ils se connaissent”.",
      "Le lien entre compétences, objectifs, modules et évaluations doit être visible, pas seulement expliqué à l’oral.",
      "Vérifier que le référentiel utilisé est à jour et correspond bien à la certification visée.",
    ],
    clientBenefit: [
      "Un tableau de correspondance clair aide à sécuriser Qualiopi.",
      "Il permet aussi de mieux expliquer la valeur de la formation aux bénéficiaires.",
      "Il rassure les financeurs et partenaires certificateurs.",
      "Il aide les formateurs à comprendre précisément ce que la formation doit préparer.",
    ],
  },
  8: {
    title: "Indicateur 8 — Positionnement et prérequis",
    summary:
      "Vérifier que les prérequis sont contrôlés lorsqu’ils existent, et que le positionnement permet de connaître le niveau, les attentes et la motivation du bénéficiaire avant l’entrée en formation.",
    questionsToAsk: [
      "Existe-t-il des prérequis pour cette prestation ?",
      "Comment l’organisme vérifie-t-il que le bénéficiaire remplit ces prérequis ?",
      "S’il n’y a pas de prérequis, cette information est-elle clairement indiquée dans les informations publiques ?",
      "Comment le niveau de connaissances du bénéficiaire est-il identifié avant l’entrée en formation ?",
      "Le positionnement couvre-t-il aussi les attentes, la motivation et le contexte du bénéficiaire ?",
    ],
    evidenceToRequest: [
      "Formulaire de positionnement ou test d’entrée.",
      "Échange email, synthèse ou compte rendu d’entretien.",
      "Scan de notes ou trace d’un entretien téléphonique.",
      "Document indiquant les prérequis ou l’absence de prérequis.",
      "Programme ou page publique liée à l’indicateur 1 mentionnant les conditions d’accès.",
    ],
    vigilancePoints: [
      "Même sans prérequis, le positionnement reste attendu : il ne sert pas seulement à dire oui ou non à l’entrée.",
      "Une vérification orale doit être tracée : Qualiopi n’a pas encore appris à lire dans les souvenirs.",
      "Le positionnement doit aider à ajuster la prestation, pas dormir dans un dossier.",
      "Si aucun prérequis n’existe, l’information doit être claire pour le futur bénéficiaire.",
      "Attention aux tests non exploités ou aux formulaires sans date ni bénéficiaire identifiable.",
    ],
    clientBenefit: [
      "Un bon positionnement évite d’inscrire quelqu’un dans une formation qui ne lui correspond pas.",
      "Il limite les abandons, les frustrations et les écarts de niveau trop importants.",
      "Il permet de personnaliser le parcours et de mieux préparer le formateur.",
      "Il améliore la satisfaction client autant qu’il sécurise Qualiopi.",
    ],
  },
  9: {
    title: "Indicateur 9 — Conditions de déroulement",
    summary:
      "Vérifier que le bénéficiaire reçoit avant la formation toutes les informations pratiques nécessaires au bon déroulement. Le fameux “je ne savais pas” est rarement une bonne preuve.",
    questionsToAsk: [
      "Quelles informations pratiques sont envoyées au bénéficiaire avant l’entrée en formation ?",
      "Le lieu, les horaires, les modalités d’accès, les contacts et les conditions pratiques sont-ils clairement indiqués ?",
      "Le livret d’accueil et le règlement intérieur sont-ils facilement accessibles ?",
      "Les convocations ou emails d’information sont-ils conservés ?",
      "Le client pourrait-il mettre le livret d’accueil et le règlement intérieur sur son site pour sécuriser une partie de l’indicateur ?",
    ],
    evidenceToRequest: [
      "Convocation ou email envoyé avant la formation.",
      "Livret d’accueil.",
      "Règlement intérieur.",
      "Page du site où les documents pratiques sont disponibles.",
      "Preuve d’envoi ou de mise à disposition : email, capture, lien, espace client.",
    ],
    vigilancePoints: [
      "Mettre le livret d’accueil et le règlement intérieur sur le site peut sécuriser une partie de la preuve.",
      "Il restera tout de même à montrer que le bénéficiaire reçoit les informations utiles avant sa formation.",
      "Les informations pratiques doivent être cohérentes avec la prestation réelle : lieu, horaires, accès, contact, matériel, distanciel si concerné.",
      "Une information disponible quelque part ne suffit pas toujours : il faut pouvoir montrer qu’elle est transmise ou facilement accessible.",
      "Attention aux documents obsolètes qui contredisent les emails ou les programmes.",
    ],
    clientBenefit: [
      "Des informations claires réduisent les questions de dernière minute.",
      "Le bénéficiaire arrive mieux préparé et plus serein.",
      "L’organisme gagne du temps en évitant les rappels répétitifs.",
      "Une logistique claire donne une impression de sérieux dès le départ.",
    ],
  },
  10: {
    title: "Indicateur 10 — Adaptation de la prestation",
    summary:
      "Vérifier comment l’organisme adapte réellement la prestation pendant sa mise en œuvre. Adapter, ce n’est pas bricoler : c’est piloter la qualité de l’expérience apprenant.",
    questionsToAsk: [
      "Quelles adaptations ont été prévues ou réalisées à partir de l’analyse du besoin et du positionnement ?",
      "Comment l’organisme adapte-t-il la prestation au niveau du bénéficiaire ?",
      "Que se passe-t-il si le rythme, les contraintes ou les besoins évoluent en cours de formation ?",
      "Comment les situations de handicap ou besoins spécifiques sont-ils pris en compte ?",
      "Les adaptations en présentiel, distanciel ou format hybride sont-elles tracées ?",
      "Les retours en cours de formation peuvent-ils conduire à une adaptation ?",
    ],
    evidenceToRequest: [
      "Déroulé pédagogique et supports déjà observés à l’indicateur 6.",
      "Traces d’adaptation : email, note, support modifié, exercice ajusté, compte rendu, suivi formateur.",
      "Exemples d’aménagement de rythme, modalité, durée, exercice ou accompagnement.",
      "Échanges avec le bénéficiaire ou le commanditaire sur une adaptation demandée.",
      "Preuve de prise en compte d’une situation de handicap si concernée.",
    ],
    vigilancePoints: [
      "Cet indicateur reprend beaucoup d’éléments de l’indicateur 6, mais demande davantage la preuve de l’adaptation réelle.",
      "Une adaptation intuitive ou orale doit être tracée pour devenir exploitable en audit.",
      "Attention aux organismes qui disent “on s’adapte toujours” mais ne peuvent montrer aucun exemple.",
      "L’adaptation doit rester cohérente avec les objectifs, pas transformer la prestation en autre chose sans trace.",
      "Les retours en cours de formation sont précieux s’ils déclenchent une action visible.",
    ],
    clientBenefit: [
      "Tracer les adaptations montre que l’organisme écoute vraiment ses bénéficiaires.",
      "Cela valorise le professionnalisme des formateurs.",
      "Le client peut mieux expliquer pourquoi une prestation a été ajustée.",
      "Une adaptation bien pilotée améliore l’expérience apprenant et réduit les risques d’abandon.",
    ],
  },
  11: {
    title: "Indicateur 11 — Évaluation des acquis",
    summary:
      "Vérifier que l’évaluation mesure réellement les objectifs annoncés. Une satisfaction positive dit que tout s’est bien passé ; une évaluation des acquis montre ce qui a été appris.",
    questionsToAsk: [
      "Quelle évaluation est réalisée en fin de formation ?",
      "Cette évaluation permet-elle de vérifier les objectifs annoncés à l’indicateur 5 ?",
      "Les résultats des évaluations sont-ils conservés ?",
      "Que fait l’organisme si un objectif n’est pas atteint ?",
      "L’évaluation est-elle différente d’un simple questionnaire de satisfaction ?",
    ],
    evidenceToRequest: [
      "Évaluation de fin de formation.",
      "Quiz, cas pratique, mise en situation, grille d’observation ou exercice corrigé.",
      "Résultats individuels ou collectifs conservés.",
      "Lien entre objectifs annoncés et critères d’évaluation.",
      "Exemple d’action prévue si les acquis ne sont pas suffisants.",
    ],
    vigilancePoints: [
      "L’évaluation de fin de formation suffit généralement si elle mesure vraiment les objectifs.",
      "Reprendre ce qui a été vu à l’indicateur 5 : objectifs et évaluation doivent se répondre.",
      "Un questionnaire de satisfaction seul n’est pas une évaluation des acquis.",
      "Les résultats doivent être conservés : une évaluation sans trace, c’est une preuve qui s’évapore.",
      "Attention aux évaluations trop générales qui ne permettent pas de savoir ce qui est acquis.",
    ],
    clientBenefit: [
      "Une vraie évaluation prouve que la formation a produit quelque chose.",
      "Elle aide le formateur à ajuster ses prochaines sessions.",
      "Elle donne au client une preuve solide de l’atteinte des compétences.",
      "Elle valorise la formation au-delà du simple “les participants étaient contents”.",
    ],
  },
  12: {
    title: "Indicateur 12 — Suivi et accompagnement des bénéficiaires",
    summary:
      "Vérifier comment l’organisme suit le bon déroulement des parcours et réagit en cas de difficulté ou d’abandon. Suivre un abandon, ce n’est pas cocher une case : c’est comprendre ce qui bloque.",
    questionsToAsk: [
      "Des abandons ou interruptions de parcours ont-ils eu lieu ?",
      "Si oui, quelles relances ou actions d’accompagnement ont été réalisées ?",
      "Quelle trace conserve l’organisme : email, appel résumé, proposition d’adaptation, réorientation, justification ?",
      "S’il n’y a pas eu d’abandon, comment l’organisme surveille-t-il quand même le bon déroulement des parcours ?",
      "Comment les difficultés sont-elles repérées avant qu’il ne soit trop tard ?",
    ],
    evidenceToRequest: [
      "Tableau de suivi des parcours ou présences.",
      "Relances envoyées en cas d’absence, retard ou décrochage.",
      "Échanges email, résumé d’appel ou compte rendu de suivi.",
      "Trace d’accompagnement proposé, adaptation, réorientation ou justification de l’abandon.",
      "Point d’étape, bilan intermédiaire ou suivi formateur.",
    ],
    vigilancePoints: [
      "En cas d’abandon, demander ce qui a été tenté avant de clôturer le dossier.",
      "S’il n’y a pas eu d’abandon, vérifier que l’organisme sait tout de même surveiller le bon déroulement.",
      "Les formations très courtes peuvent rendre l’indicateur non concerné selon le périmètre.",
      "Une relance orale doit être résumée quelque part pour devenir une preuve.",
      "Attention aux abandons justifiés uniquement par “plus de nouvelles” sans trace de relance.",
    ],
    clientBenefit: [
      "Comprendre les abandons permet d’améliorer les prochaines sessions.",
      "Le suivi aide à repérer les difficultés avant qu’elles deviennent des ruptures.",
      "Les bénéficiaires se sentent davantage accompagnés.",
      "Le client transforme un incident de parcours en information utile pour piloter sa qualité.",
    ],
  },
  13: {
    title: "Indicateur 13 — Alternance : articulation centre / entreprise",
    summary:
      "Cet indicateur concerne les formations en alternance. Il vérifie que l’organisme ne laisse pas la partie entreprise vivre sa vie dans son coin, comme un apprenti livré à une carte au trésor sans boussole.",
    questionsToAsk: [
      "Comment l’organisme organise-t-il le lien entre la formation et l’entreprise ?",
      "Les missions confiées en entreprise sont-elles connues ou anticipées ?",
      "Le rythme centre / entreprise est-il expliqué au bénéficiaire ?",
      "Existe-t-il des échanges avec l’entreprise, le tuteur ou le maître d’apprentissage ?",
      "Comment l’organisme suit-il la progression entre ce qui est appris en formation et ce qui est pratiqué en entreprise ?",
    ],
    evidenceToRequest: [
      "Livret de suivi de l’alternant ou de l’apprenti.",
      "Planning d’alternance.",
      "Échanges avec l’entreprise.",
      "Document de liaison centre / entreprise.",
      "Objectifs ou missions en entreprise.",
      "Comptes rendus de suivi, bilans ou points intermédiaires.",
    ],
    vigilancePoints: [
      "L’alternance ne se résume pas à “un coup en centre, un coup en entreprise”.",
      "Il faut montrer que le centre et l’entreprise se parlent, sinon chacun avance avec sa propre lampe torche.",
      "Les missions en entreprise doivent avoir un lien avec le parcours et les compétences visées.",
      "Un planning seul ne suffit pas toujours si aucun suivi ou échange n’est visible.",
    ],
    clientBenefit: [
      "Une bonne coordination avec l’entreprise améliore le suivi du bénéficiaire.",
      "Elle limite les ruptures de parcours et les incompréhensions.",
      "Elle renforce la crédibilité de l’organisme auprès des employeurs.",
      "Elle aide l’apprenti à comprendre le lien entre formation et terrain.",
    ],
  },
  14: {
    title:
      "Indicateur 14 — CFA : accompagnement socio-professionnel, éducatif et citoyen",
    summary:
      "Cet indicateur concerne les CFA. Il vérifie que l’apprenti n’est pas seulement accompagné sur les compétences métier, mais aussi dans son parcours global : intégration, posture professionnelle, droits, devoirs, difficultés éventuelles.",
    questionsToAsk: [
      "Comment le CFA accompagne-t-il les apprentis au-delà des cours ?",
      "Existe-t-il un accompagnement en cas de difficulté sociale, professionnelle, administrative ou éducative ?",
      "Les apprentis sont-ils informés sur leurs droits, devoirs et comportements attendus ?",
      "Le CFA propose-t-il des ressources ou relais utiles en cas de besoin ?",
      "Comment les situations sensibles sont-elles repérées et suivies ?",
    ],
    evidenceToRequest: [
      "Livret d’accueil apprenti.",
      "Supports d’information.",
      "Procédure ou trace d’accompagnement.",
      "Contacts utiles transmis aux apprentis.",
      "Traces d’entretiens, bilans ou suivis.",
      "Actions de sensibilisation à la citoyenneté, à la posture professionnelle ou à la vie en entreprise.",
    ],
    vigilancePoints: [
      "L’accompagnement ne doit pas rester une phrase du type “on est disponibles si besoin”.",
      "C’est sympathique, mais Qualiopi préfère quand la disponibilité laisse quelques traces.",
      "Les relais et contacts utiles doivent être réellement accessibles aux apprentis.",
      "Les situations sensibles doivent être suivies avec tact, mais aussi avec un minimum de traçabilité.",
    ],
    clientBenefit: [
      "Un apprenti bien accompagné décroche moins facilement.",
      "Il comprend mieux son rôle, ses droits et ses devoirs.",
      "Le CFA sécurise le parcours au-delà du simple contenu métier.",
      "C’est bon pour l’audit, mais surtout pour la réussite de l’apprenti.",
    ],
  },
  15: {
    title: "Indicateur 15 — CFA : droits, devoirs, santé et sécurité de l’apprenti",
    summary:
      "Cet indicateur concerne les CFA. Il vise à vérifier que les apprentis sont informés de leurs droits et devoirs, ainsi que des règles de santé et sécurité liées à leur statut et à leur environnement professionnel.",
    questionsToAsk: [
      "Les apprentis reçoivent-ils une information claire sur leurs droits et devoirs ?",
      "Les règles de santé et sécurité sont-elles présentées ?",
      "Les obligations liées au statut d’apprenti et de salarié sont-elles expliquées ?",
      "L’information est-elle transmise au bon moment, idéalement au démarrage du parcours ?",
      "Le CFA conserve-t-il une preuve de cette transmission ?",
    ],
    evidenceToRequest: [
      "Livret d’accueil apprenti.",
      "Règlement intérieur.",
      "Support d’information santé/sécurité.",
      "Feuille d’émargement d’une réunion d’accueil.",
      "Email de transmission.",
      "Attestation ou preuve de remise.",
      "Documents transmis par l’entreprise ou le CFA.",
    ],
    vigilancePoints: [
      "Dire “ils le savent” ne suffit pas.",
      "Qualiopi n’a pas encore développé le don de télépathie administrative : il faut une preuve que l’information a bien été remise ou présentée.",
      "La santé et sécurité doit être adaptée au contexte réel de l’apprenti.",
      "L’information doit être transmise assez tôt pour être utile, pas seulement rangée quelque part.",
    ],
    clientBenefit: [
      "Une information claire réduit les malentendus.",
      "Elle sécurise le parcours et protège l’apprenti, le CFA et l’entreprise.",
      "Elle donne au CFA une base solide si une difficulté survient.",
      "Elle rend les attentes plus lisibles pour tout le monde.",
    ],
  },
  16: {
    title: "Indicateur 16 — Conditions de présentation à la certification",
    summary:
      "Cet indicateur concerne les formations certifiantes. Il vérifie que l’organisme respecte les conditions prévues pour présenter les bénéficiaires à la certification : inscriptions, prérequis, délais, pièces, modalités, convocations, aménagements éventuels.",
    questionsToAsk: [
      "Qui inscrit le bénéficiaire à la certification ?",
      "Quelles sont les conditions de présentation à l’examen ou à l’évaluation certificative ?",
      "Les bénéficiaires sont-ils informés des démarches et échéances ?",
      "Les pièces nécessaires sont-elles collectées et conservées ?",
      "Comment les aménagements éventuels sont-ils gérés ?",
      "Le client peut-il prouver que les bénéficiaires sont bien accompagnés jusqu’à la certification ?",
    ],
    evidenceToRequest: [
      "Procédure de présentation à la certification.",
      "Modalités transmises par le certificateur.",
      "Convocations.",
      "Emails d’information.",
      "Dossiers d’inscription.",
      "Liste des pièces demandées.",
      "Calendrier d’examen ou d’évaluation.",
      "Traces d’accompagnement des bénéficiaires.",
    ],
    vigilancePoints: [
      "Une formation certifiante ne s’arrête pas au dernier jour de cours.",
      "Si personne ne sait comment le bénéficiaire arrive jusqu’à la certification, il manque un morceau du pont.",
      "Les démarches, délais et pièces demandées doivent être connus et communiqués.",
      "Les aménagements éventuels doivent être anticipés et tracés.",
    ],
    clientBenefit: [
      "Clarifier les conditions de présentation évite les ratés d’inscription.",
      "Les bénéficiaires sont rassurés sur les étapes jusqu’à la certification.",
      "L’organisme montre qu’il accompagne réellement jusqu’au bout du parcours.",
      "Le certificateur, le financeur et le bénéficiaire comprennent mieux qui fait quoi.",
    ],
  },
  17: {
    title: "Indicateur 17 — Moyens humains, techniques et environnementaux",
    summary:
      "Vérifier que l’organisme sait présenter les moyens réellement mobilisés pour réaliser ses prestations. Ce qui est évident dans la tête du dirigeant doit exister quelque part dans les preuves.",
    questionsToAsk: [
      "Quels moyens humains interviennent réellement dans les prestations ?",
      "Quels formateurs internes, externes, assistants, fonctions support ou membres de la direction participent à la réalisation ou au pilotage ?",
      "Quels moyens matériels sont utilisés pendant les formations ou accompagnements ?",
      "L’environnement de formation est-il adapté : salle, équipements, plateforme, outils numériques, visio, LMS ?",
      "En distanciel, quels outils permettent de former, accompagner, échanger et transmettre les ressources ?",
    ],
    evidenceToRequest: [
      "Liste des formateurs internes et externes mobilisés.",
      "Présentation des assistants, direction ou fonctions support lorsqu’ils interviennent vraiment dans la prestation.",
      "Photos de salle, plan, inventaire ou liste du matériel : tables, chaises, vidéoprojecteur, ordinateurs, matériel métier spécifique.",
      "Preuves des outils numériques : plateforme en ligne, LMS, outil visio, espaces partagés.",
      "Bail, devis, convention d’occupation, facture de location ou facture de plateforme en ligne.",
    ],
    vigilancePoints: [
      "Ne pas lister des personnes qui n’interviennent jamais dans les prestations : les moyens doivent être réels, pas décoratifs.",
      "Les moyens matériels doivent être adaptés au type de prestation et aux objectifs annoncés.",
      "En distanciel, moyens matériels et environnementaux peuvent se rejoindre : plateforme, outil visio, LMS, documents partagés.",
      "Une salle ou une plateforme doit pouvoir être prouvée par une trace simple : photo, facture, contrat, capture ou accès.",
      "Attention aux prestations métiers qui nécessitent du matériel spécifique : l’absence de preuve peut vite fragiliser l’indicateur.",
    ],
    clientBenefit: [
      "Identifier les moyens montre que la prestation n’est pas improvisée.",
      "Une logistique claire rassure les clients et les financeurs.",
      "Le client pilote mieux ses ressources : qui fait quoi, avec quels outils, dans quel environnement.",
      "Qualiopi aime les preuves. Le client aime quand ça lui simplifie la vie. Le bon document fait les deux.",
    ],
  },
  18: {
    title: "Indicateur 18 — Coordination des intervenants",
    summary:
      "Vérifier que les personnes impliquées dans les prestations savent qui fait quoi et comment elles se coordonnent. Une coordination visible évite que tout repose dans la tête du dirigeant.",
    questionsToAsk: [
      "Qui intervient réellement dans la réalisation, l’administration, le suivi ou le pilotage des prestations ?",
      "Existe-t-il un organigramme limité aux personnes utiles à l’activité de formation ?",
      "Les rôles sont-ils clarifiés : formateur, responsable pédagogique, administratif, référent handicap, direction ?",
      "Comment les informations circulent-elles entre l’organisme et les intervenants internes ou externes ?",
      "Quelles traces existent lorsqu’il n’y a pas de réunion formelle ?",
    ],
    evidenceToRequest: [
      "Organigramme opérationnel centré sur les personnes qui interviennent réellement.",
      "Fiches de poste ou fiches de fonction : formateur, responsable pédagogique, responsable administratif, référent handicap, direction si elle pilote.",
      "Comptes rendus de réunions si disponibles.",
      "Emails, SMS, WhatsApp, messages de coordination, briefs ou échanges avec intervenants externes.",
      "Modèles de fiches de fonction proposés ou adaptés si le client en dispose.",
    ],
    vigilancePoints: [
      "Éviter l’organigramme décoratif avec des personnes qui n’ont aucun rôle dans les prestations.",
      "Les fiches de fonction doivent décrire ce que les personnes font vraiment, pas une version idéale jamais utilisée.",
      "L’absence de réunion n’est pas forcément bloquante si d’autres traces de coordination existent.",
      "Les échanges informels peuvent aider, mais il faut les conserver : capture, email de synthèse, brief écrit.",
      "Les intervenants externes doivent recevoir les informations nécessaires pour agir de façon cohérente avec l’organisme.",
    ],
    clientBenefit: [
      "Une coordination claire réduit les oublis et les doubles discours.",
      "Le dirigeant n’est plus le seul disque dur de l’organisation.",
      "Les intervenants savent ce qui est attendu, ce qui rend la prestation plus régulière.",
      "C’est plus solide pour Qualiopi et beaucoup plus confortable pour piloter l’activité.",
    ],
  },
  19: {
    title: "Indicateur 19 — Ressources pédagogiques et accompagnement",
    summary:
      "Vérifier que les supports existent, qu’ils sont accessibles aux bénéficiaires et que les contacts utiles sont disponibles. Avoir des supports ne suffit pas : il faut prouver qu’ils arrivent jusqu’aux apprenants.",
    questionsToAsk: [
      "Quels supports pédagogiques sont remis ou mis à disposition des bénéficiaires ?",
      "Comment l’organisme prouve-t-il que les supports ont bien été transmis ou rendus accessibles ?",
      "Les supports sont-ils disponibles sur une plateforme, par email, via un espace apprenant ou un lien d’accès ?",
      "En distanciel, les coordonnées des référents pédagogiques ou techniques sont-elles visibles ?",
      "Où le bénéficiaire trouve-t-il de l’aide s’il rencontre une difficulté pédagogique ou technique ?",
    ],
    evidenceToRequest: [
      "Supports de formation : diaporama, livret, fiche outil, exercices, ressources complémentaires.",
      "Preuve de remise ou mise à disposition : email, plateforme, attestation, lien d’accès, espace apprenant.",
      "Capture ou accès à la plateforme si les supports sont en ligne.",
      "Convocation, livret d’accueil, email de démarrage ou site mentionnant les référents pédagogiques ou techniques.",
      "Coordonnées utiles pour le distanciel : contact pédagogique, support technique, procédure en cas de problème.",
    ],
    vigilancePoints: [
      "Un support dans l’ordinateur du formateur n’est pas automatiquement une ressource mise à disposition.",
      "Il faut une preuve que le bénéficiaire peut accéder aux ressources.",
      "En distanciel, les contacts pédagogiques et techniques doivent être faciles à retrouver.",
      "Les supports doivent être cohérents avec les objectifs et le déroulé pédagogique.",
      "Attention aux liens non testés, plateformes fermées ou espaces apprenants sans preuve d’accès.",
    ],
    clientBenefit: [
      "Des supports bien transmis réduisent les questions et les relances.",
      "Le bénéficiaire sait où retrouver les ressources après la séance.",
      "Les contacts visibles sécurisent l’expérience, surtout en distanciel.",
      "Une preuve bien rangée aujourd’hui, c’est une sueur froide en moins le jour de l’audit.",
    ],
  },
  20: {
    title: "Indicateur 20 — CFA : référents, mobilité et conseil de perfectionnement",
    summary:
      "Cet indicateur concerne les CFA. Il vérifie que l’organisme dispose des fonctions et instances spécifiques attendues : référents, appui à la mobilité, handicap, conseil de perfectionnement et organisation du suivi.",
    questionsToAsk: [
      "Le CFA a-t-il identifié un référent handicap ?",
      "Existe-t-il une personne ou fonction dédiée à la mobilité nationale ou internationale ?",
      "Le conseil de perfectionnement est-il constitué ?",
      "Les rôles sont-ils clairement définis ?",
      "Les apprentis savent-ils à qui s’adresser ?",
      "Les informations sont-elles visibles ou facilement accessibles ?",
    ],
    evidenceToRequest: [
      "Fiche référent handicap.",
      "Fiche référent mobilité.",
      "Liste des membres du conseil de perfectionnement.",
      "Comptes rendus ou traces de réunions.",
      "Livret d’accueil apprenti.",
      "Organigramme ou fiches de fonction.",
      "Supports d’information transmis aux apprentis.",
    ],
    vigilancePoints: [
      "Attention aux référents “fantômes” : une personne peut être nommée, mais encore faut-il que son rôle soit clair, connu et un minimum tracé.",
      "Les apprentis doivent savoir à qui s’adresser, pas seulement l’équipe administrative.",
      "Le conseil de perfectionnement doit laisser des traces exploitables.",
      "Les fiches de fonction doivent décrire des responsabilités réelles, pas uniquement des titres.",
    ],
    clientBenefit: [
      "Des référents bien identifiés évitent que toutes les questions remontent au hasard à la même personne.",
      "C’est plus clair pour les apprentis et plus confortable pour l’équipe.",
      "Le CFA pilote mieux les sujets handicap, mobilité et amélioration du parcours.",
      "C’est plus solide pour l’audit et plus lisible au quotidien.",
    ],
  },
  21: {
    title: "Indicateur 21 — Compétences des intervenants",
    summary:
      "Vérifier que les compétences des formateurs et intervenants sont documentées et cohérentes avec les prestations réalisées. L’expertise réelle mérite mieux qu’un “on sait faire” oral.",
    questionsToAsk: [
      "Qui intervient dans les formations ou accompagnements concernés ?",
      "Quelles compétences, expériences ou qualifications justifient leur intervention ?",
      "Les compétences sont-elles cohérentes avec les prestations réellement réalisées ?",
      "Pour les intervenants externes, quels éléments l’organisme collecte-t-il avant de leur confier une mission ?",
      "Les preuves sont-elles conservées et faciles à retrouver ?",
    ],
    evidenceToRequest: [
      "CV des formateurs ou intervenants.",
      "Diplômes, certifications, titres ou habilitations utiles.",
      "Attestations de formation ou justificatifs d’expérience.",
      "Dossier intervenant interne ou externe.",
      "Éléments de vérification pour les prestataires externes : CV, références, diplômes, attestations, échange de validation.",
    ],
    vigilancePoints: [
      "Les preuves peuvent être simples, mais elles doivent exister.",
      "Un bon CV ne suffit pas toujours si la prestation exige une qualification ou une compétence spécifique.",
      "Les intervenants externes doivent être vérifiés comme les internes : la sous-traitance ne fait pas disparaître l’exigence.",
      "Les compétences doivent correspondre à ce qui est réellement enseigné, pas seulement à un intitulé général.",
      "Attention aux dossiers formateurs jamais mis à jour.",
    ],
    clientBenefit: [
      "Des compétences bien documentées rassurent les clients, financeurs et auditeurs.",
      "Le client valorise l’expertise réelle de son organisme.",
      "Un dossier intervenant clair facilite la délégation et la sélection des formateurs.",
      "Une preuve bien rangée aujourd’hui, c’est une sueur froide en moins le jour de l’audit.",
    ],
  },
  22: {
    title: "Indicateur 22 — Développement des compétences",
    summary:
      "Vérifier que l’organisme entretient ses compétences dans le temps. Se former régulièrement évite de laisser les pratiques prendre la poussière.",
    questionsToAsk: [
      "Quelles formations, webinaires ou événements professionnels ont été suivis sur les 12 derniers mois ?",
      "Des inscriptions à de futures formations sont-elles prévues ?",
      "Les compétences développées concernent-elles la pédagogie, le métier enseigné, la réglementation, les outils numériques, l’accessibilité ou la qualité ?",
      "Comment l’organisme décide-t-il des compétences à développer ?",
      "Les apprentissages réalisés ont-ils un effet visible sur les pratiques ?",
    ],
    evidenceToRequest: [
      "Attestations de formation des 12 derniers mois.",
      "Inscriptions ou confirmations à de futures formations.",
      "Webinaires, événements professionnels ou replays suivis, par exemple Webikeo.",
      "Plan ou tableau simple de développement des compétences.",
      "Preuves d’application : support mis à jour, nouvel outil utilisé, procédure améliorée, méthode pédagogique ajustée.",
    ],
    vigilancePoints: [
      "L’absence de formation prévue fragilise l’indicateur : proposer au minimum des webinaires ou événements professionnels en ligne.",
      "Le développement des compétences ne se limite pas au métier : il peut aussi concerner la qualité, l’accessibilité, le numérique ou la pédagogie.",
      "Une inscription future peut aider, mais elle doit être crédible et suivie.",
      "Attention aux attestations anciennes qui ne montrent pas un entretien régulier des compétences.",
      "Il faut montrer que l’organisme entretient ses compétences dans le temps, pas uniquement quand l’audit approche.",
    ],
    clientBenefit: [
      "Se former régulièrement garde l’offre crédible et à jour.",
      "Le client peut mieux répondre aux évolutions de son métier et des attentes bénéficiaires.",
      "Les formateurs gagnent en confort et en légitimité.",
      "Qualiopi aime les traces. Le client aime quand ces traces lui servent vraiment.",
    ],
  },
  23: {
    title: "Indicateur 23 — Veille légale et réglementaire",
    summary:
      "Vérifier que la veille porte bien sur la formation professionnelle et qu’elle est exploitée. Une source sans action reste une lecture ; une veille utile change quelque chose.",
    questionsToAsk: [
      "Quelles sources l’organisme suit-il pour la réglementation de la formation professionnelle ?",
      "La veille porte-t-elle bien sur le domaine formation, et pas seulement sur le métier enseigné ?",
      "Qui consulte ces sources et à quelle fréquence ?",
      "Quelle évolution réglementaire a déjà entraîné une action concrète ?",
      "Si l’organisme est récent, quelle veille l’a aidé à obtenir son NDA ou à se mettre en conformité ?",
    ],
    evidenceToRequest: [
      "Tableau ou document de veille légale et réglementaire.",
      "Sources institutionnelles, articles spécialisés, newsletters ou sources professionnelles.",
      "Ressources Selen Editions si le client les utilise.",
      "Exemple d’exploitation : obtention du NDA, mise à jour d’une procédure, adaptation d’un document, mise en conformité avec le référentiel national qualité.",
      "Trace indiquant source, date, information retenue et action réalisée.",
    ],
    vigilancePoints: [
      "La veille légale doit concerner la formation professionnelle, pas uniquement la réglementation du métier enseigné.",
      "S’il n’y a aucune source de veille, proposer les services de mise en conformité Qualiopi.",
      "Pour un organisme récent, un article expliquant comment obtenir son NDA peut être une source, avec exploitation “obtention du NDA”.",
      "Exemple Selen : source “selen-editions.fr”, exploitation “mise en conformité avec le référentiel national qualité”.",
      "Vérifier qu’il existe une exploitation, pas seulement une liste de liens.",
    ],
    clientBenefit: [
      "Une veille légale utile évite les mauvaises surprises.",
      "Le client reste dans les clous sans découvrir les changements trop tard.",
      "Les actions de mise en conformité deviennent plus faciles à justifier.",
      "Une veille non exploitée, c’est une collection de liens. Une veille exploitée, c’est une amélioration visible.",
    ],
  },
  24: {
    title: "Indicateur 24 — Veille métier et pédagogique",
    summary:
      "Vérifier que l’organisme suit les évolutions de son métier, de la pédagogie et des outils utiles à ses prestations, puis qu’il transforme au moins une information en amélioration concrète.",
    questionsToAsk: [
      "Quelles sources l’organisme suit-il pour son métier ou ses pratiques pédagogiques ?",
      "Ces sources concernent-elles les contenus, méthodes, outils ou pratiques professionnelles utiles à la prestation ?",
      "Qu’est-ce qui a été appris récemment grâce à cette veille ?",
      "Quelle amélioration concrète a été réalisée à partir d’une source de veille ?",
      "Comment l’organisme conserve-t-il la trace entre source consultée et changement réalisé ?",
    ],
    evidenceToRequest: [
      "Articles en ligne, livres, conférences, séminaires, webinaires, podcasts professionnels ou échanges entre pairs.",
      "Tableau ou document de veille métier et pédagogique.",
      "Trace d’une amélioration reliée à une source.",
      "Support, programme, outil, méthode ou ressource pédagogique mis à jour.",
      "Compte rendu d’échange professionnel ou note interne expliquant ce qui a été retenu.",
    ],
    vigilancePoints: [
      "La veille doit concerner le métier, la pédagogie, les pratiques professionnelles ou les outils utiles à la prestation.",
      "Une source lue mais jamais utilisée reste une jolie pile d’informations, pas une preuve d’amélioration.",
      "Il faut relier au moins une amélioration concrète à une source de veille.",
      "Les échanges entre pairs peuvent être utiles, mais ils doivent laisser une trace exploitable.",
      "Attention aux tableaux de veille remplis uniquement pour l’audit, sans effet réel sur l’activité.",
    ],
    clientBenefit: [
      "La veille métier améliore les contenus, les méthodes et la qualité perçue des formations.",
      "Le client garde une offre vivante et crédible.",
      "Les formateurs restent connectés aux pratiques réelles du terrain.",
      "La veille devient un moteur d’évolution, pas juste une corvée Qualiopi.",
    ],
  },
  25: {
    title: "Indicateur 25 — Exploitation de la veille",
    summary:
      "Vérifier ce qui a concrètement changé grâce à la veille. La veille prend tout son sens quand elle produit une amélioration ; sinon, elle dort tranquillement dans un tableau.",
    questionsToAsk: [
      "Quelle amélioration a été réalisée grâce à une veille récente ?",
      "Le client peut-il montrer la source qui a déclenché cette amélioration ?",
      "Qu’est-ce qui a changé dans l’organisme : support, outil, questionnaire, procédure, programme, méthode ?",
      "Existe-t-il une version avant/après lorsque des supports ont été modifiés ?",
      "Un nouveau logiciel ou outil a-t-il été adopté à la suite d’une démonstration, recommandation, webinaire ou article ?",
    ],
    evidenceToRequest: [
      "Versions avant/après d’un support ou document modifié.",
      "Trace de changement d’outil, nouveau logiciel ou nouvelle procédure.",
      "Source de l’amélioration : développeur du logiciel, démonstration, article, webinaire ou recommandation professionnelle.",
      "Support mis à jour, questionnaire amélioré, procédure ajoutée, adaptation pédagogique ou programme modifié.",
      "Note ou tableau reliant source, décision et action réalisée.",
    ],
    vigilancePoints: [
      "Si des supports sont améliorés grâce à une veille, conserver les versions avant/après.",
      "L’utilisation d’un nouveau logiciel peut être une exploitation de veille si la source et la décision sont tracées.",
      "Demander ce qui a concrètement changé, pas seulement ce qui a été lu.",
      "Une exploitation doit être visible dans les pratiques ou les documents.",
      "Attention aux veilles abondantes mais jamais transformées en action.",
    ],
    clientBenefit: [
      "L’exploitation de la veille rend l’amélioration continue concrète.",
      "Le client peut montrer qu’il apprend, ajuste et progresse.",
      "Les supports et méthodes restent vivants.",
      "Une veille exploitée améliore l’offre ; une veille non exploitée collectionne les liens.",
    ],
  },
  26: {
    title: "Indicateur 26 — Handicap et accessibilité",
    summary:
      "Vérifier que l’organisme sait accueillir, orienter et adapter lorsqu’une situation de handicap se présente. Une politique handicap bien complétée peut sécuriser durablement cet indicateur.",
    questionsToAsk: [
      "Une politique handicap existe-t-elle et est-elle accessible ?",
      "L’organisme connaît-il les interlocuteurs locaux à mobiliser en cas de besoin ?",
      "Les coordonnées Agefiph, Cap emploi, MDPH et FIPHFP sont-elles disponibles ?",
      "L’organisme est-il inscrit à Ressource Handicap Formation ou prévoit-il de le faire ?",
      "Un contact a-t-il été pris avec l’Agefiph pour présenter l’organisme et son catalogue ?",
      "La politique handicap peut-elle être publiée sur le site pour sécuriser aussi l’indicateur 1 ?",
    ],
    evidenceToRequest: [
      "Document de politique handicap complété.",
      "Coordonnées Agefiph, Cap emploi, MDPH et FIPHFP.",
      "Preuve d’inscription ou de démarche Ressource Handicap Formation.",
      "Email envoyé à l’Agefiph pour présenter l’organisme et son catalogue de formation.",
      "Page du site ou document public présentant l’accueil et l’orientation des personnes en situation de handicap.",
      "Modèle de politique handicap proposé si le client n’en a pas encore.",
    ],
    vigilancePoints: [
      "Le client doit avoir au minimum les coordonnées des quatre structures : Agefiph, Cap emploi, MDPH, FIPHFP.",
      "Si la politique handicap est absente, proposer le document prévu dans les modèles.",
      "Ce document peut aussi aider l’indicateur 1 s’il est mis sur le site.",
      "L’Agefiph est généralement accessible et aidante : conseiller un mail simple de présentation.",
      "Ressource Handicap Formation est un bon point d’appui si l’inscription n’est pas encore faite.",
    ],
    clientBenefit: [
      "L’accessibilité handicap n’est pas seulement une exigence Qualiopi.",
      "Elle rassure les bénéficiaires et montre que l’organisme sait orienter au bon endroit.",
      "Elle aide l’équipe à réagir plus sereinement lorsqu’une situation se présente.",
      "Une politique handicap claire permet d’accueillir plus largement et de professionnaliser la réponse.",
    ],
  },
  27: {
    title: "Indicateur 27 — Sous-traitance et intervenants externes",
    summary:
      "Vérifier comment l’organisme cadre les formateurs, prestataires sous-traitants ou salariés portés qui réalisent ses prestations. Prêter les clés du château, oui, mais avec les bonnes règles et les bonnes traces.",
    questionsToAsk: [
      "L’organisme intervient-il lui-même comme sous-traitant ou en portage, ou fait-il appel à ses propres sous-traitants ?",
      "Pour cet indicateur, l’organisme mobilise-t-il des personnes externes pour réaliser tout ou partie des prestations ?",
      "Quels contrats, conventions, lettres de mission ou accords encadrent ces interventions ?",
      "Les exigences qualité Qualiopi sont-elles transmises aux sous-traitants ?",
      "Les rôles, responsabilités, modalités d’intervention et preuves attendues sont-ils clairement définis ?",
      "Comment l’organisme suit-il la qualité du travail réalisé par les sous-traitants ?",
    ],
    evidenceToRequest: [
      "Contrats, conventions, lettres de mission ou accords avec les sous-traitants.",
      "Charte qualité, consignes Qualiopi ou document d’engagement transmis aux intervenants externes.",
      "Fiches de mission précisant rôle, responsabilités, modalités d’intervention et preuves attendues.",
      "CV, compétences ou justificatifs des intervenants externes si non vus ailleurs.",
      "Traces de suivi qualité : échanges, retours bénéficiaires, contrôle de documents, bilan d’intervention.",
    ],
    vigilancePoints: [
      "Bien distinguer deux situations : l’organisme intervient lui-même en sous-traitance/portage, ou il fait appel à ses propres sous-traitants.",
      "Pour l’indicateur 27, regarder surtout le deuxième cas : des personnes externes réalisent-elles les prestations pour le compte de l’organisme ?",
      "La sous-traitance ne transfère pas la responsabilité qualité : l’organisme doit garder la maîtrise.",
      "Un contrat commercial seul ne suffit pas toujours si les exigences qualité et preuves attendues ne sont jamais transmises.",
      "Attention aux intervenants externes réguliers traités comme de simples contacts informels sans cadrage écrit.",
    ],
    clientBenefit: [
      "Bien cadrer la sous-traitance évite les mauvaises surprises.",
      "Le client garde la maîtrise de sa qualité, même quand il ne réalise pas tout lui-même.",
      "Les intervenants savent exactement ce qui est attendu, ce qui fluidifie la prestation.",
      "Un cadre clair protège l’organisme, le sous-traitant et le bénéficiaire.",
    ],
  },
  28: {
    title:
      "Indicateur 28 — Périodes en situation de travail et partenaires socio-économiques",
    summary:
      "Vérifier comment l’organisme prépare, suit et exploite les périodes en entreprise, AFEST, stages ou mises en pratique. Qualiopi aime les preuves ; les apprenants aiment savoir où ils mettent les pieds.",
    questionsToAsk: [
      "Les prestations comprennent-elles des périodes en entreprise, AFEST, stages ou mises en pratique en situation de travail ?",
      "Comment l’organisme choisit-il les partenaires ou structures d’accueil ?",
      "Comment les partenaires, tuteurs ou référents sont-ils informés des objectifs de la période ?",
      "Quelles consignes sont données pour accompagner le bénéficiaire sur le terrain ?",
      "Comment l’organisme suit-il le déroulement de la période en situation de travail ?",
      "Pour les CFA ou l’alternance, quels outils de suivi spécifiques des apprentis sont utilisés ?",
    ],
    evidenceToRequest: [
      "Convention de stage, convention de mise en situation ou document AFEST.",
      "Livret de suivi, carnet de liaison ou outil de suivi terrain.",
      "Échanges avec l’entreprise, le tuteur, le référent ou la structure d’accueil.",
      "Objectifs de la période en situation de travail.",
      "Consignes données au tuteur ou référent.",
      "Bilan, retour d’expérience ou évaluation de la période.",
      "Outils de suivi spécifiques des apprentis si CFA ou alternance.",
    ],
    vigilancePoints: [
      "Ne pas confondre périodes en situation de travail avec alternance ou apprentissage, même si certains outils peuvent se croiser.",
      "Si aucune période en situation de travail n’existe, l’indicateur peut être non concerné selon le périmètre.",
      "La partie terrain ne doit pas devenir une zone floue : objectifs, consignes et suivi doivent être visibles.",
      "Une entreprise partenaire doit comprendre ce qui est attendu, pas seulement accueillir le bénéficiaire.",
      "Attention aux stages ou mises en pratique sans bilan ni retour exploitable.",
    ],
    clientBenefit: [
      "Un bon suivi des périodes en entreprise sécurise le parcours du bénéficiaire.",
      "Le client garde le lien entre la formation et ce qui se passe sur le terrain.",
      "Les partenaires savent mieux accompagner et faire remonter les informations utiles.",
      "La partie pratique devient une vraie ressource pédagogique, pas une parenthèse hors radar.",
    ],
  },
  29: {
    title: "Indicateur 29 — CFA : insertion professionnelle et poursuite de parcours",
    summary:
      "Cet indicateur concerne les CFA. Il vise à vérifier que l’organisme ne s’arrête pas à la formation, mais accompagne aussi l’apprenti vers la suite : insertion professionnelle, poursuite d’études, orientation ou sécurisation du parcours.",
    questionsToAsk: [
      "Comment le CFA accompagne-t-il les apprentis vers l’emploi ou la poursuite d’études ?",
      "Des informations sont-elles transmises sur les débouchés, passerelles ou suites possibles ?",
      "Le CFA suit-il les parcours après la formation ?",
      "Des actions sont-elles menées avec les entreprises ou partenaires ?",
      "Les apprentis savent-ils à qui s’adresser pour préparer la suite ?",
    ],
    evidenceToRequest: [
      "Supports sur les débouchés.",
      "Informations sur les poursuites d’études ou passerelles.",
      "Actions avec les entreprises.",
      "Suivi post-formation.",
      "Questionnaires de devenir.",
      "Ateliers emploi, CV, entretien, orientation.",
      "Traces d’échanges avec partenaires ou employeurs.",
    ],
    vigilancePoints: [
      "La fin de la formation ne doit pas être une porte qui claque.",
      "L’auditeur cherchera à voir comment le CFA prépare ou suit la suite du parcours.",
      "Les informations sur les débouchés doivent être concrètes et accessibles.",
      "Le suivi post-formation peut être simple, mais il doit laisser une trace.",
    ],
    clientBenefit: [
      "Accompagner l’après-formation valorise le CFA.",
      "Cela améliore la relation avec les entreprises.",
      "Les apprentis repartent avec une trajectoire plus claire.",
      "C’est aussi un excellent argument commercial : “on ne vous forme pas juste, on vous aide à avancer”.",
    ],
  },
  30: {
    title: "Indicateur 30 — Appréciations des parties prenantes",
    summary:
      "Vérifier que l’organisme sollicite les retours des parties prenantes concernées et qu’il les exploite vraiment. Les retours clients, même quand ils piquent un peu, sont souvent de très bons GPS.",
    questionsToAsk: [
      "Quelles parties prenantes sont sollicitées : bénéficiaires, formateurs, entreprises, donneurs d’ordre, financeurs ?",
      "À quel moment les appréciations sont-elles recueillies ?",
      "Que fait l’organisme lorsqu’une partie prenante ne répond pas ?",
      "Les questionnaires contiennent-ils au moins un champ d’expression libre ?",
      "Comment les réponses sont-elles analysées et utilisées après collecte ?",
      "Existe-t-il une procédure simple de sollicitation et de relance ?",
    ],
    evidenceToRequest: [
      "Questionnaires ou formulaires envoyés aux bénéficiaires.",
      "Sollicitations des formateurs, entreprises, donneurs d’ordre ou financeurs lorsque ces parties sont concernées.",
      "Preuve d’au moins une relance en cas de non-réponse.",
      "Résultats ou exports des réponses collectées.",
      "Analyse des retours et actions décidées si nécessaire.",
      "Procédure de sollicitation des appréciations et de relance, avec modèle disponible si besoin.",
    ],
    vigilancePoints: [
      "Toutes les parties prenantes concernées doivent être sollicitées, pas uniquement les bénéficiaires.",
      "Un questionnaire sans champ libre, c’est un thermomètre sans graduation : on sait vaguement que quelque chose se passe, mais pas vraiment quoi.",
      "Une absence de réponse n’est pas bloquante si le client peut prouver qu’il a relancé.",
      "Les réponses ne doivent pas dormir dans un coin : il faut montrer qu’elles sont regardées et exploitées.",
      "Attention aux questionnaires envoyés mais jamais analysés.",
    ],
    clientBenefit: [
      "Collecter les appréciations permet de repérer ce qui fonctionne et ce qui agace.",
      "Les retours renforcent la qualité perçue et la relation client.",
      "Une procédure simple évite d’oublier les relances.",
      "Les appréciations deviennent une source concrète d’amélioration, pas seulement une formalité Qualiopi.",
    ],
  },
  31: {
    title: "Indicateur 31 — Réclamations et difficultés",
    summary:
      "Vérifier que l’organisme sait recevoir, suivre et traiter une réclamation. Une réclamation bien traitée, ce n’est pas un drame : c’est une amélioration qui frappe à la porte.",
    questionsToAsk: [
      "Comment une partie prenante peut-elle déposer une réclamation ?",
      "Le moyen de réclamation est-il visible : email, formulaire, contact désigné, procédure, livret ou règlement ?",
      "Les bénéficiaires, financeurs, entreprises, donneurs d’ordre, formateurs et partenaires peuvent-ils être concernés ?",
      "Existe-t-il un tableau, registre ou outil de suivi des réclamations ?",
      "Que fait l’organisme s’il n’a jamais reçu de réclamation ?",
      "Le règlement intérieur ou le livret d’accueil mentionne-t-il la procédure de réclamation ?",
    ],
    evidenceToRequest: [
      "Article ou mention sur le dépôt de réclamation dans le règlement intérieur ou le livret d’accueil.",
      "Adresse email, formulaire, contact désigné ou procédure de réclamation.",
      "Tableau, registre, document interne ou outil de suivi.",
      "Exemples de réclamations traitées si elles existent.",
      "Suivi indiquant date, personne ou partie prenante concernée, sujet, traitement, clôture et actions correctives.",
      "Procédure expliquant comment traiter une réclamation même lorsqu’il n’y en a pas encore eu.",
    ],
    vigilancePoints: [
      "Le vrai risque n’est pas d’avoir une réclamation : c’est de ne pas savoir quoi en faire.",
      "Une réclamation peut venir de nombreuses parties prenantes, pas seulement des bénéficiaires.",
      "S’il n’y a aucune réclamation, le client doit quand même expliquer comment il la traiterait.",
      "Le suivi doit montrer la clôture et les actions correctives si nécessaire.",
      "Une mention claire dans le livret d’accueil ou le règlement intérieur sécurise fortement l’indicateur.",
    ],
    clientBenefit: [
      "Un canal de réclamation clair rassure les parties prenantes.",
      "Le client transforme les difficultés en actions utiles.",
      "Un suivi bien tenu protège l’organisme en cas de tension.",
      "Traiter les réclamations améliore la qualité sans attendre que le problème se répète.",
    ],
  },
  32: {
    title: "Indicateur 32 — Amélioration continue",
    summary:
      "Vérifier que l’organisme regarde ce qui se passe, décide quoi améliorer et garde une trace. L’amélioration continue, ce n’est pas avoir tout parfait : c’est prouver qu’on corrige et qu’on avance.",
    questionsToAsk: [
      "Quelles sources alimentent l’amélioration : satisfaction, retours, réclamations, incidents, non-conformités, veille, difficultés rencontrées ?",
      "Existe-t-il un tableau ou document de suivi des améliorations passées, en cours et prévues ?",
      "Pour chaque amélioration, connaît-on l’origine, l’action décidée, le responsable, l’échéance et l’état d’avancement ?",
      "Le client peut-il montrer une amélioration réelle, même simple ?",
      "Comment le résultat est-il vérifié lorsque l’action est terminée ?",
      "Qu’est-ce qui a changé concrètement dans les pratiques ou les documents ?",
    ],
    evidenceToRequest: [
      "Tableau ou plan d’amélioration continue.",
      "Analyse de satisfaction, retours de parties prenantes, réclamations, incidents ou non-conformités.",
      "Résultats de veille ayant déclenché une action.",
      "Suivi indiquant origine de l’amélioration, action décidée, responsable, échéance, état d’avancement et résultat obtenu.",
      "Exemples d’amélioration : support modifié, questionnaire amélioré, information clarifiée sur le site, procédure ajoutée, nouvel outil, meilleure relance, adaptation pédagogique.",
    ],
    vigilancePoints: [
      "L’amélioration doit être réelle, même simple.",
      "Un tableau vide ou jamais suivi ne suffit pas.",
      "Il faut pouvoir relier une source à une action : retour client, veille, incident, non-conformité ou difficulté.",
      "Une action terminée doit idéalement montrer un résultat ou une vérification.",
      "L’objectif n’est pas de tout rendre parfait, mais d’arrêter de piloter uniquement au ressenti.",
    ],
    clientBenefit: [
      "L’organisme pilote avec des indices plutôt qu’au feeling.",
      "Les problèmes deviennent des occasions de progresser.",
      "Les améliorations visibles rassurent les clients, financeurs et auditeurs.",
      "La qualité devient un outil de gestion concret, pas un classeur oublié.",
    ],
  },
};
