"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import SelenBadge from "@/components/ui/SelenBadge";
import SelenButton from "@/components/ui/SelenButton";
import SelenCard, { SelenCardTitle } from "@/components/ui/SelenCard";

type ReminderStatus = "draft" | "ready" | "sent" | "ignored" | "postponed";
type ReminderRow = { id:string; client_email:string; dossier_id:string|null; reminder_type:string; status:ReminderStatus; subject:string; body_html:string; body_text:string; due_at:string; sent_at:string|null; created_at:string; updated_at:string; metadata:Record<string,unknown>|null };
type ReminderEvent = { id:string; reminder_id:string; event_type:string; agent_email:string|null; subject:string|null; body_text:string|null; created_at:string };

const STATUS_FILTERS=[{value:"active",label:"À traiter"},{value:"ready",label:"Prêtes"},{value:"draft",label:"Brouillons"},{value:"postponed",label:"Reportées"},{value:"sent",label:"Envoyées"},{value:"ignored",label:"Ignorées"},{value:"all",label:"Toutes"}];
function metadataText(row:ReminderRow,key:string){const value=row.metadata?.[key];return typeof value==="string"?value:typeof value==="number"?String(value):""}
function formatDate(value?:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function formatType(type:string){const labels:Record<string,string>={preaudit_incomplete_15_days:"Préaudit incomplet",audit_blanc_booking_reminder_7_days:"Prise de RDV Review",audit_blanc_48h_reminder:"Rappel 48h Review",nda_inactive_9_days:"NDA inactif",daily_signature_pending_72h:"Signature Daily"};return labels[type]??type}
function formatStatus(status:ReminderStatus){return {draft:"Brouillon",ready:"Prête",sent:"Envoyée",ignored:"Ignorée",postponed:"Reportée"}[status]}
function statusVariant(status:ReminderStatus){if(status==="sent")return "success";if(status==="ignored")return "neutral";if(status==="postponed")return "warn";if(status==="draft")return "status";return "info"}

export default function AgentRelancesPage(){
 const[reminders,setReminders]=useState<ReminderRow[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState("");const[error,setError]=useState("");const[search,setSearch]=useState("");const[statusFilter,setStatusFilter]=useState("active");const[editing,setEditing]=useState<Record<string,ReminderRow>>({});const[busyId,setBusyId]=useState("");const[generating,setGenerating]=useState(false);const[historyByReminder,setHistoryByReminder]=useState<Record<string,ReminderEvent[]>>({});const[openHistoryId,setOpenHistoryId]=useState("");
 const loadReminders=useCallback(async()=>{setLoading(true);setError("");const response=await fetch("/agent/api/reminders/list",{cache:"no-store"});const result=await response.json();if(!response.ok){setError(result.error??"Impossible de charger les relances.");setLoading(false);return}const rows=(result.reminders??[]) as ReminderRow[];setReminders(rows);setEditing(Object.fromEntries(rows.map(row=>[row.id,{...row}] )));setLoading(false)},[]);
 useEffect(()=>{void loadReminders()},[loadReminders]);
 async function loadHistory(reminderId:string){if(openHistoryId===reminderId){setOpenHistoryId("");return}setOpenHistoryId(reminderId);if(historyByReminder[reminderId])return;const response=await fetch(`/agent/api/reminders/history?reminderId=${encodeURIComponent(reminderId)}`,{cache:"no-store"});const result=await response.json();if(!response.ok){setError(result.error??"Impossible de charger l’historique.");return}setHistoryByReminder(current=>({...current,[reminderId]:(result.events??[]) as ReminderEvent[]}))}
 async function generateNow(){setGenerating(true);setNotice("");setError("");const response=await fetch("/agent/api/reminders/generate",{method:"POST"});const result=await response.json();setGenerating(false);if(!response.ok){setError(result.error??"Impossible de générer les relances.");return}setNotice(`${result.result.created} relance(s) préparée(s).`);await loadReminders()}
 async function updateReminder(id:string,action:"save"|"ignore"|"postpone"){setBusyId(id);setNotice("");setError("");const row=editing[id];const response=await fetch("/agent/api/reminders/update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reminderId:id,action,subject:row?.subject,bodyHtml:row?.body_html,bodyText:row?.body_text,status:row?.status})});const result=await response.json();setBusyId("");if(!response.ok){setError(result.error??"Action impossible.");return}setNotice(action==="postpone"?"Relance reportée de 7 jours.":action==="ignore"?"Relance ignorée.":"Relance enregistrée.");await loadReminders()}
 async function sendReminder(id:string){setBusyId(id);setNotice("");setError("");const row=editing[id];const response=await fetch("/agent/api/reminders/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reminderId:id,subject:row?.subject,bodyHtml:row?.body_html,bodyText:row?.body_text})});const result=await response.json();setBusyId("");if(!response.ok){setError(result.error??"Envoi impossible.");return}setNotice(result.sent?"Relance envoyée.":result.error??"Relance validée, mais email non envoyé.");await loadReminders()}
 function updateDraft(id:string,field:"subject"|"body_text",value:string){setEditing(current=>({...current,[id]:{...current[id],[field]:value}}))}
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return reminders.filter(row=>{const statusOk=statusFilter==="active"?["draft","ready","postponed"].includes(row.status):statusFilter==="all"||row.status===statusFilter;const textOk=!q||[row.client_email,row.reminder_type,row.subject,row.dossier_id??"",metadataText(row,"reason")].join(" ").toLowerCase().includes(q);return statusOk&&textOk})},[reminders,search,statusFilter]);
 return <main style={s.page}><header style={s.header}><div><p style={s.eyebrow}>Studio agent</p><h1 style={s.title}>Relances clients</h1><p style={s.subtitle}>Les relances visibles ici suivent la même attribution que le tableau de bord et Pilotage Daily. Après 24 h ouvrées sans traitement, elles deviennent accessibles à l’équipe.</p></div><SelenButton onClick={()=>void generateNow()} disabled={generating}>{generating?"Génération...":"Générer maintenant"}</SelenButton></header>
 {notice?<div style={s.notice}>{notice}</div>:null}{error?<div style={s.error}>Erreur : {error}</div>:null}
 <SelenCard><SelenCardTitle>Filtres</SelenCardTitle><div style={s.toolbar}><input value={search} type="search" onChange={e=>setSearch(e.target.value)} placeholder="Rechercher client, dossier, raison..." style={s.input}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} style={s.input}>{STATUS_FILTERS.map(f=><option key={f.value} value={f.value}>{f.label}</option>)}</select></div></SelenCard>
 <section style={s.list}>{loading?<SelenCard>Chargement des relances...</SelenCard>:filtered.length===0?<SelenCard>Aucune relance ne correspond aux filtres.</SelenCard>:filtered.map(row=>{const draft=editing[row.id]??row;const busy=busyId===row.id;return <SelenCard key={row.id}><div style={s.rowHeader}><div><div style={s.badges}><SelenBadge variant="type" dot>{formatType(row.reminder_type)}</SelenBadge><SelenBadge variant={statusVariant(row.status)} dot>{formatStatus(row.status)}</SelenBadge></div><h2 style={s.itemTitle}>{row.client_email}</h2></div><div style={s.actions}>{row.dossier_id?<Link href={`/agent/dossiers/${row.dossier_id}`} style={{textDecoration:"none"}}><SelenButton type="button" size="sm" variant="ghost">Voir le dossier</SelenButton></Link>:null}<SelenButton type="button" size="sm" variant="ghost" onClick={()=>void loadHistory(row.id)}>Historique</SelenButton></div></div>
 <div style={s.grid}><Info label="Prestation" value={formatType(row.reminder_type)}/><Info label="Raison" value={metadataText(row,"reason")||"—"}/><Info label="Échéance" value={formatDate(row.due_at)}/><Info label="Dossier" value={row.dossier_id??"—"}/></div>
 <div style={s.editor}><label style={s.field}>Sujet<input value={draft.subject??""} onChange={e=>updateDraft(row.id,"subject",e.target.value)} style={s.input}/></label><label style={s.field}>Brouillon texte<textarea value={draft.body_text??""} onChange={e=>updateDraft(row.id,"body_text",e.target.value)} rows={5} style={s.textarea}/></label></div>
 <div style={s.actions}><SelenButton type="button" size="sm" variant="secondary" disabled={busy||row.status==="sent"} onClick={()=>void updateReminder(row.id,"save")}>Enregistrer</SelenButton><SelenButton type="button" size="sm" disabled={busy||row.status==="sent"} onClick={()=>void sendReminder(row.id)}>Envoyer</SelenButton><SelenButton type="button" size="sm" variant="ghost" disabled={busy||row.status==="sent"} onClick={()=>void updateReminder(row.id,"ignore")}>Ignorer</SelenButton><SelenButton type="button" size="sm" variant="ghost" disabled={busy||row.status==="sent"} onClick={()=>void updateReminder(row.id,"postpone")}>Reporter 7 j</SelenButton></div>
 {openHistoryId===row.id?<div style={s.history}><strong>Historique</strong>{(historyByReminder[row.id]??[]).length===0?<p style={s.muted}>Aucun événement enregistré.</p>:(historyByReminder[row.id]??[]).map(event=><div key={event.id} style={s.historyItem}><span>{formatDate(event.created_at)}</span><span>{event.event_type}</span><span>{event.agent_email??"automatique"}</span></div>)}</div>:null}</SelenCard>})}</section></main>
}
function Info({label,value}:{label:string;value:string}){return <div><div style={s.infoLabel}>{label}</div><div style={s.infoValue}>{value}</div></div>}
const s:Record<string,React.CSSProperties>={page:{maxWidth:1180,margin:"0 auto",padding:"28px",color:"var(--selen-text)"},header:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",flexWrap:"wrap",marginBottom:20},eyebrow:{fontSize:10,fontWeight:800,letterSpacing:".18em",textTransform:"uppercase",color:"var(--selen-gold2)",margin:0},title:{fontFamily:"var(--font-display)",fontSize:32,margin:"6px 0"},subtitle:{maxWidth:760,color:"var(--selen-text2)",lineHeight:1.6,margin:0},notice:{margin:"12px 0",padding:12,border:"1px solid var(--selen-border)",borderRadius:10},error:{margin:"12px 0",padding:12,color:"var(--selen-danger)"},toolbar:{display:"flex",gap:10,flexWrap:"wrap",marginTop:12},input:{minHeight:38,padding:"8px 10px",border:"1px solid var(--selen-border)",borderRadius:8,background:"var(--selen-bg2)",color:"var(--selen-text)",minWidth:220},textarea:{width:"100%",padding:10,border:"1px solid var(--selen-border)",borderRadius:8,background:"var(--selen-bg2)",color:"var(--selen-text)",resize:"vertical"},list:{display:"grid",gap:12,marginTop:16},rowHeader:{display:"flex",justifyContent:"space-between",gap:14,alignItems:"flex-start",flexWrap:"wrap"},badges:{display:"flex",gap:6,flexWrap:"wrap"},itemTitle:{fontSize:18,margin:"8px 0 0"},actions:{display:"flex",gap:8,flexWrap:"wrap",marginTop:12},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,margin:"16px 0"},infoLabel:{fontSize:10,textTransform:"uppercase",color:"var(--selen-text3)",fontWeight:800},infoValue:{fontSize:13,marginTop:4,overflowWrap:"anywhere"},editor:{display:"grid",gap:10},field:{display:"grid",gap:6,fontSize:12,fontWeight:700},history:{marginTop:16,paddingTop:14,borderTop:"1px solid var(--selen-border)"},historyItem:{display:"grid",gridTemplateColumns:"minmax(150px,.8fr) 1fr 1fr",gap:8,fontSize:11,padding:"7px 0",borderBottom:"1px solid var(--selen-border)"},muted:{color:"var(--selen-text3)",fontSize:12}};
