"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type DocumentRow = { id:string; organisation_id:string; document_type:string; status:string; version:number; logical_name:string; created_at:string; metadata?:Record<string,unknown>|null; organisations?:{name?:string|null}|null };
const labels:Record<string,string>={training_program:"Programme",training_agreement:"Convention",convocation:"Convocation",registration_positioning:"Inscription & positionnement"};
const statusLabels:Record<string,string>={to_check:"À vérifier",to_validate:"À valider",validated:"Validé",correction_requested:"Correction demandée",published:"Publié",signed:"Signé",draft:"Brouillon",active:"Actif",archived:"Archivé"};

export default function DailyPretrainingReviewPage(){
  const [documents,setDocuments]=useState<DocumentRow[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [filter,setFilter]=useState("attention");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/agent/api/daily/pretraining-documents",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Chargement impossible.");setDocuments(d.documents??[]);}catch(c){setError(c instanceof Error?c.message:"Chargement impossible.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const visible=useMemo(()=>documents.filter((d)=>filter==="all"||["to_check","to_validate","correction_requested"].includes(d.status)),[documents,filter]);
  async function review(id:string,action:"validate"|"request_correction"){const note=action==="request_correction"?window.prompt("Motif ou correction demandée :","")??"":"";setError("");setMessage("");const r=await fetch("/agent/api/daily/pretraining-documents",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action,note})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error??"Action impossible.");return;}setMessage(action==="validate"?"Document validé.":"Correction demandée.");await load();}
  return <main style={{maxWidth:1180,margin:"0 auto",padding:28}}><p style={{fontSize:12,fontWeight:700,color:"var(--selen-text2)"}}>SELEN DAILY</p><h1>Documents préformation</h1><p style={{color:"var(--selen-text2)",maxWidth:760}}>Contrôle des programmes, conventions, convocations et documents d’inscription/positionnement générés depuis les dossiers Daily.</p>
    <div style={{display:"flex",gap:8,margin:"18px 0"}}><button onClick={()=>setFilter("attention")} disabled={filter==="attention"}>À traiter</button><button onClick={()=>setFilter("all")} disabled={filter==="all"}>Tous</button></div>
    {error&&<div style={{padding:12,border:"1px solid #b24c3d",marginBottom:12}}>{error}</div>}{message&&<div style={{padding:12,border:"1px solid var(--selen-border)",marginBottom:12}}>{message}</div>}
    {loading?<p>Chargement…</p>:<section style={{display:"grid",gap:12}}>{visible.length===0?<div style={{padding:18,border:"1px solid var(--selen-border)",borderRadius:12}}>Aucun document dans cette vue.</div>:visible.map((doc)=><article key={doc.id} style={{border:"1px solid var(--selen-border)",borderRadius:12,padding:16,background:"var(--selen-bg2)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{labels[doc.document_type]??doc.document_type}</strong>{typeof doc.metadata?.learner_name==="string"?` · ${doc.metadata.learner_name}`:""}<div style={{fontSize:12,color:"var(--selen-text2)",marginTop:4}}>{doc.organisations?.name??"Organisme"} · v{doc.version} · {statusLabels[doc.status]??doc.status}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a href={`/agent/api/daily/pretraining-documents/download?id=${encodeURIComponent(doc.id)}`} target="_blank" rel="noreferrer">Télécharger</a>{!["validated","published","signed","archived"].includes(doc.status)&&<><button onClick={()=>void review(doc.id,"validate")}>Valider</button><button onClick={()=>void review(doc.id,"request_correction")}>Demander une correction</button></>}</div></div>{typeof doc.metadata?.review_note==="string"&&doc.metadata.review_note?<p style={{marginTop:10,fontSize:12}}>Note : {doc.metadata.review_note}</p>:null}</article>)}</section>}
  </main>;
}
