import { revalidatePath } from "next/cache";
import { createSupabaseAdminClient } from "@/lib/server/supabaseAdmin";
import { createClient } from "@/lib/supabase/server";

async function currentAgentProfileId(){
 "use server";
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const admin=createSupabaseAdminClient();const{data}=await admin.from("agent_profiles").select("id").or(`user_id.eq.${user.id}${user.email?`,email.eq.${user.email}`:""}`).eq("is_active",true).limit(1).maybeSingle();return data?.id??null;
}
async function createWatch(formData:FormData){
 "use server";
 const type=String(formData.get("watch_type")??"");const title=String(formData.get("title")??"").trim();const url=String(formData.get("article_url")??"").trim();if(!["regulatory","pedagogy_technology"].includes(type)||!title||!url)return;const admin=createSupabaseAdminClient();await admin.from("daily_watch_entries").insert({watch_type:type,title,article_url:url,published_at:new Date().toISOString(),created_by:await currentAgentProfileId()});revalidatePath("/agent/daily/qualite");
}
async function forceUsage(formData:FormData){
 "use server";
 const watchId=String(formData.get("watch_id")??"");const improvement=String(formData.get("improvement")??"").trim();const target=String(formData.get("organisation_id")??"all");if(!watchId||!improvement)return;const admin=createSupabaseAdminClient();let organisationIds:string[]=[];if(target==="all"){const{data}=await admin.from("organisations").select("id").eq("status","active");organisationIds=(data??[]).map(x=>x.id)}else organisationIds=[target];const agentId=await currentAgentProfileId();const now=new Date().toISOString();if(organisationIds.length){await admin.from("daily_organisation_watch_entries").upsert(organisationIds.map(organisation_id=>({organisation_id,watch_entry_id:watchId,interested:true,interested_at:now,improvement_note:improvement,forced_by_studio:true,forced_by_agent_profile_id:agentId,forced_at:now,updated_at:now})),{onConflict:"organisation_id,watch_entry_id"})}revalidatePath("/agent/daily/qualite");
}

export default async function DailyQualityStudioPage(){
 const admin=createSupabaseAdminClient();const[{data:watches},{data:organisations},{data:usages}]=await Promise.all([admin.from("daily_watch_entries").select("id,watch_type,title,article_url,published_at,status").order("published_at",{ascending:false}),admin.from("organisations").select("id,name,legal_name,status").eq("status","active").order("name"),admin.from("daily_organisation_watch_entries").select("watch_entry_id,interested,forced_by_studio,improvement_note,organisation_id")]);const usageRows=usages??[];
 return <main style={s.page}><header><p style={s.kicker}>Selen Studio · Daily</p><h1 style={s.h1}>Qualité & veilles</h1><p style={s.muted}>Publie les veilles communes Selen et trace les améliorations appliquées aux organismes Daily.</p></header><section style={s.grid}><article style={s.card}><h2>Publier une veille commune</h2><form action={createWatch} style={s.form}><label>Type<select name="watch_type" style={s.input}><option value="regulatory">Veille réglementaire</option><option value="pedagogy_technology">Veille pédagogique & technologique</option></select></label><label>Titre de l'article<input name="title" required style={s.input}/></label><label>Lien de l'article<input name="article_url" type="url" required style={s.input}/></label><button style={s.primary}>Publier dans les tableaux clients</button></form></article><article style={s.card}><h2>Forcer une amélioration</h2><p style={s.muted}>À utiliser lorsqu'une évolution Selen a réellement été appliquée pour les organismes concernés.</p><form action={forceUsage} style={s.form}><label>Veille<select name="watch_id" required style={s.input}><option value="">Choisir</option>{(watches??[]).filter(w=>w.status==="active").map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label><label>Organismes<select name="organisation_id" style={s.input}><option value="all">Tous les clients Daily actifs</option>{(organisations??[]).map(o=><option key={o.id} value={o.id}>{o.legal_name||o.name||o.id}</option>)}</select></label><label>Amélioration réalisée<textarea name="improvement" required rows={4} style={s.input}/></label><button style={s.primary}>Enregistrer l'exploitation</button></form></article></section><section style={s.card}><h2>Veilles publiées</h2>{(watches??[]).length===0?<p style={s.muted}>Aucune veille commune pour le moment.</p>:<div style={s.list}>{(watches??[]).map(w=>{const rows=usageRows.filter(u=>u.watch_entry_id===w.id),interested=rows.filter(u=>u.interested).length,forced=rows.filter(u=>u.forced_by_studio).length;return <article key={w.id} style={s.row}><div><span style={s.badge}>{w.watch_type==="regulatory"?"Réglementaire":"Pédagogique & techno"}</span><h3 style={{margin:"6px 0"}}>{w.title}</h3><a href={w.article_url} target="_blank" rel="noreferrer" style={s.link}>Ouvrir l'article ↗</a></div><div style={s.stats}><strong>{interested}</strong><span>organisme(s) intéressé(s)</span><strong>{forced}</strong><span>exploitation(s) imposée(s) par Studio</span></div></article>})}</div>}</section></main>
}
const s:Record<string,React.CSSProperties>={page:{maxWidth:1180,margin:"0 auto",padding:"24px 28px 60px",color:"var(--selen-text)"},kicker:{fontSize:10,textTransform:"uppercase",letterSpacing:".2em",color:"var(--selen-gold)"},h1:{fontFamily:"var(--font-display)",fontSize:32,margin:"6px 0"},muted:{color:"var(--selen-text2)",lineHeight:1.6,fontSize:13},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:14,margin:"22px 0"},card:{border:"1px solid var(--selen-border)",borderRadius:"var(--radius-md)",background:"var(--selen-bg2)",padding:18,marginBottom:14},form:{display:"grid",gap:10},input:{display:"block",width:"100%",marginTop:5,border:"1px solid var(--selen-border)",borderRadius:6,background:"var(--selen-bg3)",color:"var(--selen-text)",padding:10},primary:{width:"fit-content",border:"1px solid var(--selen-gold2)",borderRadius:6,background:"var(--selen-gold2)",color:"var(--selen-bg)",padding:"9px 12px",fontWeight:800,cursor:"pointer"},list:{display:"grid",gap:10},row:{display:"grid",gridTemplateColumns:"minmax(0,1fr) 210px",gap:16,border:"1px solid var(--selen-border)",borderRadius:8,padding:14,background:"var(--selen-bg3)"},badge:{fontSize:10,textTransform:"uppercase",color:"var(--selen-gold2)"},link:{color:"var(--selen-gold2)",fontWeight:700,textDecoration:"none"},stats:{display:"grid",gridTemplateColumns:"40px 1fr",gap:"4px 8px",alignContent:"start",fontSize:12}};
