import Link from "next/link";
import { createSupabaseAdminClient } from "@/lib/server/supabaseAdmin";
import { requireSupportAgent } from "@/app/agent/api/support/_utils";
import { getDailyAgentTasks } from "@/lib/server/dailyAgentTasks";
import { getStudioClientFollowups } from "@/lib/server/studioClientFollowups";
import SelenCard, { SelenCardTitle } from "@/components/ui/SelenCard";

function formatDate(value?:string|null){return value?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Date inconnue"}
export default async function AgentDailyPage(){
 const auth=await requireSupportAgent();if(!auth.ok)return <main className="daily-page" style={s.page}><p>Accès refusé.</p></main>;
 const admin=createSupabaseAdminClient();const[{data:profile},{data:adminUser}]=await Promise.all([admin.from("agent_profiles").select("id,role").eq("email",auth.email).eq("is_active",true).maybeSingle(),admin.from("selen_admin_users").select("role").eq("email",auth.email).eq("is_active",true).maybeSingle()]);const role=(adminUser?.role==="admin"||profile?.role==="admin"?"admin":"agent") as "admin"|"agent";
 let tasks;let followups;try{[tasks,followups]=await Promise.all([getDailyAgentTasks({id:profile?.id??null,role}),getStudioClientFollowups({id:profile?.id??null,role},{dailyOnly:true})])}catch(error){return <main className="daily-page" style={s.page}><p style={s.error}>Impossible de charger le pilotage Daily : {error instanceof Error?error.message:"erreur inconnue"}</p></main>}
 return <main className="daily-page" style={s.page}>
  <header className="daily-hero" style={s.header}><div><p style={s.eyebrow}>Selen Daily</p><h1 style={s.h1}>Pilotage Daily</h1><p style={s.lead}>Deux files seulement : ce que l’agent doit traiter et ce qu’une partie prenante doit encore faire. Ces mêmes alertes sont reprises sur l’accueil général du Studio, sans créer de faux doublons dans la messagerie.</p></div><div style={s.counters}><div style={s.counter}><strong>{tasks.length}</strong><span>tâches</span></div><div style={s.counter}><strong>{followups.length}</strong><span>relances</span></div></div></header>
  <SelenCard style={s.ruleCard}><strong>Règles de pilotage</strong><p style={s.ruleText}>Une tâche Daily reste rattachée à l’agent responsable de l’organisme. Après 72 h, elle devient traitable par toute l’équipe sans changer l’assignation. Même règle pour une relance client : après 72 h dans la file « Clients à relancer », elle devient visible par tous les agents.</p></SelenCard>
  <section style={s.columns}>
   <div><div style={s.sectionHead}><h2 style={s.h2}>Tâches à faire</h2><span style={s.pill}>{tasks.length}</span></div>{tasks.length===0?<SelenCard style={s.empty}><SelenCardTitle>Rien ne demande ton intervention</SelenCardTitle><p style={s.muted}>Aucune action Daily agent n’est ouverte.</p></SelenCard>:<div style={s.list}>{tasks.map(item=><SelenCard key={item.id} style={s.card}><div style={s.cardHead}><div><div style={s.badges}><span style={s.badge}>{item.reason}</span>{item.overdueShared?<span style={{...s.badge,...s.badgeOverdue}}>72 h · équipe</span>:null}</div><SelenCardTitle>{item.title}</SelenCardTitle><p style={s.org}>{item.organisation}</p></div><span style={s.date}>{formatDate(item.createdAt)}</span></div><p style={s.detail}>{item.detail}</p><div style={s.actions}>{item.kind==="assignment"?(role==="admin"?<Link href={item.href} style={s.primary}>Assigner un agent →</Link>:<form method="post" action="/agent/api/daily/organisation-assignment"><input type="hidden" name="organisation_id" value={item.organisationId}/><button type="submit" style={s.primaryButton}>Me l’assigner →</button></form>):<Link href={item.href} style={s.primary}>Traiter maintenant →</Link>}</div></SelenCard>)}</div>}</div>
   <div><div style={s.sectionHead}><h2 style={s.h2}>Clients à relancer</h2><span style={s.pill}>{followups.length}</span></div>{followups.length===0?<SelenCard style={s.empty}><SelenCardTitle>Aucune relance Daily</SelenCardTitle><p style={s.muted}>Aucune action n’est actuellement attendue d’un apprenant, formateur, entreprise ou autre partie prenante.</p></SelenCard>:<div style={s.list}>{followups.map(item=><SelenCard key={item.id} style={s.card}><div style={s.cardHead}><div><div style={s.badges}><span style={{...s.badge,...s.badgeClient}}>Partie prenante</span>{item.overdueShared?<span style={{...s.badge,...s.badgeOverdue}}>72 h · équipe</span>:null}</div><SelenCardTitle>{item.title}</SelenCardTitle></div><span style={s.date}>{formatDate(item.dueAt)}</span></div><p style={s.detail}>{item.detail}</p><Link href={item.href} style={s.secondary}>Ouvrir le dossier →</Link></SelenCard>)}</div>}</div>
  </section>
 </main>
}
const s:Record<string,React.CSSProperties>={page:{maxWidth:1180,margin:"0 auto",padding:"28px 28px 70px",color:"var(--selen-text)"},header:{display:"flex",justifyContent:"space-between",gap:22,alignItems:"center",marginBottom:18,flexWrap:"wrap"},eyebrow:{margin:0,fontSize:10,fontWeight:800,letterSpacing:".18em",textTransform:"uppercase",color:"var(--selen-gold2)"},h1:{margin:"6px 0 5px",fontFamily:"var(--font-display)",fontSize:32},h2:{margin:0,fontSize:18},lead:{margin:0,maxWidth:760,lineHeight:1.65,color:"var(--selen-text2)",fontSize:14},counters:{display:"flex",gap:8},counter:{minWidth:82,display:"grid",justifyItems:"center",padding:"11px 14px",border:"1px solid var(--selen-border)",borderRadius:12,background:"var(--selen-bg2)"},ruleCard:{marginBottom:16,padding:15},ruleText:{margin:"5px 0 0",color:"var(--selen-text2)",fontSize:12,lineHeight:1.55},columns:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(360px,1fr))",gap:16},sectionHead:{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,margin:"4px 0 10px"},pill:{minWidth:30,height:30,borderRadius:999,display:"grid",placeItems:"center",padding:"0 8px",border:"1px solid var(--selen-border)",color:"var(--selen-gold2)",fontWeight:800},list:{display:"grid",gap:10},card:{padding:16},cardHead:{display:"flex",justifyContent:"space-between",gap:14,alignItems:"flex-start"},badges:{display:"flex",gap:7,flexWrap:"wrap",marginBottom:8},badge:{display:"inline-block",padding:"4px 8px",borderRadius:999,background:"rgba(201,148,58,.14)",color:"var(--selen-gold2)",fontSize:10,fontWeight:800},badgeClient:{background:"rgba(83,132,166,.12)",color:"var(--selen-info)"},badgeOverdue:{background:"rgba(180,78,70,.16)",color:"var(--selen-danger)"},org:{margin:"5px 0 0",fontSize:12,color:"var(--selen-text3)"},date:{fontSize:10,color:"var(--selen-text3)",whiteSpace:"nowrap"},detail:{margin:"12px 0",lineHeight:1.55,fontSize:12,color:"var(--selen-text2)"},actions:{display:"flex",gap:8,flexWrap:"wrap"},primary:{display:"inline-flex",alignItems:"center",minHeight:34,padding:"0 11px",borderRadius:8,background:"var(--selen-gold2)",color:"var(--selen-bg)",textDecoration:"none",fontWeight:800,fontSize:12},primaryButton:{display:"inline-flex",alignItems:"center",minHeight:34,padding:"0 11px",borderRadius:8,border:0,background:"var(--selen-gold2)",color:"var(--selen-bg)",fontWeight:800,fontSize:12,cursor:"pointer"},secondary:{display:"inline-flex",alignItems:"center",minHeight:34,padding:"0 11px",borderRadius:8,border:"1px solid var(--selen-border)",color:"var(--selen-text)",textDecoration:"none",fontWeight:700,fontSize:12},empty:{padding:22},muted:{margin:"6px 0 0",lineHeight:1.55,color:"var(--selen-text2)",fontSize:12},error:{color:"var(--selen-danger)"}};
